language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install -n

  # This part is to make selenium work
  # Notice that you can also use PhantomJS
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
  - java -jar selenium-server-standalone-2.28.0.jar > /dev/null &
  - sleep 5

notifications:
    # email:
    #     - developer@example.com

script:
    - bin/phpspec run
    - bin/behat --no-snippets --verbose
